archiv/urls.py
from django.urls import path
from . import views
from . import copy_views
from . import geojson_views

app_name = "archiv"

urlpatterns = [
    path(
        "monumentprotection/detail/<int:pk>",
        views.MonumentProtectionDetailView.as_view(),
        name="monumentprotection_detail",
    ),
    path(
        "monumentprotection/create/",
        views.MonumentProtectionCreate.as_view(),
        name="monumentprotection_create",
    ),
    path(
        "monumentprotection/edit/<int:pk>",
        views.MonumentProtectionUpdate.as_view(),
        name="monumentprotection_edit",
    ),
    path(
        "monumentprotection/delete/<int:pk>",
        views.MonumentProtectionDelete.as_view(),
        name="monumentprotection_delete",
    ),
    path(
        "archent/detail/<int:pk>",
        views.ArchEntDetailView.as_view(),
        name="archent_detail",
    ),
    path("archent/create/", views.ArchEntCreate.as_view(), name="archent_create"),
    path(
        "archent/edit/<int:pk>",
        views.ArchEntUpdate.as_view(),
        name="archent_edit",
    ),
    path(
        "archent/delete/<int:pk>",
        views.ArchEntDelete.as_view(),
        name="archent_delete",
    ),
    path("site-geojson/", geojson_views.site_geojson, name="site_geojson"),
    path(
        "site/detail/<int:pk>",
        views.SiteDetailView.as_view(),
        name="site_detail",
    ),
    path("site/create/", views.SiteCreate.as_view(), name="site_create"),
    path("site/edit/<int:pk>", views.SiteUpdate.as_view(), name="site_edit"),
    path("site/delete/<int:pk>", views.SiteDelete.as_view(), name="site_delete"),
    path(
        "period/detail/<int:pk>",
        views.PeriodDetailView.as_view(),
        name="period_detail",
    ),
    path("period/create/", views.PeriodCreate.as_view(), name="period_create"),
    path(
        "period/edit/<int:pk>",
        views.PeriodUpdate.as_view(),
        name="period_edit",
    ),
    path(
        "period/delete/<int:pk>",
        views.PeriodDelete.as_view(),
        name="period_delete",
    ),
    path(
        "altname/detail/<int:pk>",
        views.AltNameDetailView.as_view(),
        name="altname_detail",
    ),
    path("altname/create/", views.AltNameCreate.as_view(), name="altname_create"),
    path(
        "altname/edit/<int:pk>",
        views.AltNameUpdate.as_view(),
        name="altname_edit",
    ),
    path(
        "altname/delete/<int:pk>",
        views.AltNameDelete.as_view(),
        name="altname_delete",
    ),
    path(
        "researchevent/detail/<int:pk>",
        views.ResearchEventDetailView.as_view(),
        name="researchevent_detail",
    ),
    path(
        "researchevent/create/",
        views.ResearchEventCreate.as_view(),
        name="researchevent_create",
    ),
    path(
        "researchevent/edit/<int:pk>",
        views.ResearchEventUpdate.as_view(),
        name="researchevent_edit",
    ),
    path(
        "researchevent/delete/<int:pk>",
        views.ResearchEventDelete.as_view(),
        name="researchevent_delete",
    ),
    path(
        "researchquestion/detail/<int:pk>",
        views.ResearchQuestionDetailView.as_view(),
        name="researchquestion_detail",
    ),
    path(
        "researchquestion/create/",
        views.ResearchQuestionCreate.as_view(),
        name="researchquestion_create",
    ),
    path(
        "researchquestion/edit/<int:pk>",
        views.ResearchQuestionUpdate.as_view(),
        name="researchquestion_edit",
    ),
    path(
        "researchquestion/delete/<int:pk>",
        views.ResearchQuestionDelete.as_view(),
        name="researchquestion_delete",
    ),
    path("copy-poly/", copy_views.copy_site_poly_view, name="copy_poly"),
]

bib/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = "bib"

urlpatterns = [
    path(
        "reference/detail/<int:pk>",
        views.ReferenceDetailView.as_view(),
        name="reference_detail",
    ),
    path(
        "reference/edit/<int:pk>",
        views.ReferenceUpdate.as_view(),
        name="reference_edit",
    ),
    path(
        "reference/delete/<int:pk>",
        views.ReferenceDelete.as_view(),
        name="reference_delete",
    ),
    path(
        "reference/create/",
        views.ReferenceCreate.as_view(),
        name="reference_create",
    ),
    path("references/", views.ReferenceListView.as_view(), name="browse_references"),
]

iad/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework import routers
from bib.api_views import ZotItemViewSet

from vocabs import api_views
from archiv import api_views as archiv_api_views
from shapes import api_views as shapes_api_vies

router = routers.DefaultRouter()
router.register(r"skoslabels", api_views.SkosLabelViewSet)
router.register(r"skosnamespaces", api_views.SkosNamespaceViewSet)
router.register(r"skosconceptschemes", api_views.SkosConceptSchemeViewSet)
router.register(r"skosconcepts", api_views.SkosConceptViewSet)
router.register(r"ZotItem", ZotItemViewSet)
router.register(r"sites", archiv_api_views.SiteViewSet)
router.register(r"municipalities", shapes_api_vies.MunicipalityViewSet)


urlpatterns = [
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("admin/", admin.site.urls),
    path("browsing/", include("browsing.urls", namespace="browsing")),
    path("vocabs/", include("vocabs.urls", namespace="vocabs")),
    path("vocabs-ac/", include("vocabs.dal_urls", namespace="vocabs-ac")),
    path("archiv-ac/", include("archiv.dal_urls", namespace="archiv-ac")),
    path("entities-ac/", include("entities.dal_urls", namespace="entities-ac")),
    path("entities/", include("entities.urls", namespace="entities")),
    path("shapes/", include("shapes.urls", namespace="shapes")),
    path("shapes-ac/", include("shapes.dal_urls", namespace="shapes-ac")),
    path("bib/", include("bib.urls", namespace="bib")),
    path("bib-ac/", include("bib.dal_urls", namespace="bib-ac")),
    path("archiv/", include("archiv.urls", namespace="archiv")),
    path("checks/", include("checks.urls", namespace="checks")),
    path("", include("webpage.urls", namespace="webpage")),
]

archiv/models.py
import reversion
import json

from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.gis.db import models
from django.contrib.gis.db.models import Union
from django.contrib.postgres.fields import IntegerRangeField
from django.core.serializers import serialize
from django.db.models import Max, Min

from psycopg2.extras import NumericRange

from idprovider.models import IdProvider
from entities.models import Place, Person, Institution
from vocabs.models import SkosConcept
from bib.models import Reference
from shapes.models import Municipality


def modify_fields(**kwargs):
    def wrap(cls):
        for field, prop_dict in kwargs.items():
            for prop, val in prop_dict.items():
                setattr(cls._meta.get_field(field), prop, val)
        return cls

    return wrap


VALUE_STATUS_CHOICES = (
    ("1 - high", "1 - high"),
    ("2 - middle", "2 - middle"),
    ("3 - low", "3 - low"),
)

BOOLEAN_CHOICES = ((True, "Yes"), (False, "No"))


@reversion.register()
class AltName(IdProvider):
    label = models.CharField(
        blank=True, null=True, max_length=250, verbose_name="A name tag"
    )
    language = models.CharField(
        blank=True, null=True, max_length=3, verbose_name="ISO639"
    )

    def __str__(self):
        if self.language:
            return "{} ({})".format(self.label, self.language)
        else:
            return "{}".format(self.label)

    @classmethod
    def get_listview_url(self):
        return reverse("browsing:browse_archivaltnames")

    @classmethod
    def get_createview_url(self):
        return reverse("archiv:altname_create")

    def get_next(self):
        next = AltName.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = AltName.objects.filter(id__lt=self.id).order_by("-id")
        if prev:
            return prev.first().id
        return False

    def get_absolute_url(self):
        return reverse("archiv:altname_detail", kwargs={"pk": self.id})


class IadBaseClass(IdProvider):
    """A class for shared properties"""

    identifier = models.CharField(
        blank=True, null=True, max_length=250, verbose_name="Identifier"
    )
    name = models.CharField(
        blank=True, null=True, max_length=250, verbose_name="The objects name"
    )
    alt_name = models.ManyToManyField(
        AltName,
        blank=True,
        verbose_name="Alternative Name",
        help_text="Another name of the site (another spelling, language, alias name etc.).",
    )
    alt_id = models.CharField(
        blank=True,
        null=True,
        max_length=250,
        verbose_name="Alternative ID",
        help_text="Any other official identifier of this entity.",
    )
    description = models.TextField(
        blank=True, null=True, verbose_name="Description of the object."
    )
    comment = models.TextField(
        blank=True,
        null=True,
        help_text="""Any noteworthy general information about the object
        that cannot be expressed in other fields.""",
        verbose_name="Comment",
    )
    public = models.BooleanField(
        default=False,
        verbose_name="Public",
        choices=BOOLEAN_CHOICES,
        help_text="Should this entry (and all related entries) be public\
        or only visible to the account holders? Can be made public\
        only after data-check was completed.",
    )
    literature = models.ManyToManyField(
        Reference,
        blank=True,
        verbose_name="Literature",
        help_text="Add publication references",
    )
    polygon = models.MultiPolygonField(blank=True, null=True)
    polygon_proxy = models.BooleanField(
        default=False,
        verbose_name="No precise polygon",
        choices=BOOLEAN_CHOICES,
        help_text="Please set to 'Yes' in case the polygon is merely a place holder",
    )
    centroid = models.PointField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.polygon and not self.centroid:
            cent = self.polygon.centroid
            self.centroid = cent
        super().save(*args, **kwargs)

    @classmethod
    def get_points(self):
        model_name = self.__name__
        ct = ContentType.objects.get(
            app_label="archiv", model=model_name.lower()
        ).model_class()
        geojson = serialize(
            "geojson",
            ct.objects.all(),
            geometry_field="centroid",
            fields=(
                "name",
                "pk",
            ),
        )
        return geojson

    @classmethod
    def get_shapes(self):
        model_name = self.__name__
        ct = ContentType.objects.get(
            app_label="archiv", model=model_name.lower()
        ).model_class()
        geojson = serialize(
            "geojson",
            ct.objects.all(),
            geometry_field="polygon",
            fields=(
                "name",
                "pk",
            ),
        )
        return geojson

    @classmethod
    def get_convex_hull(self):
        if Site.objects.exclude(polygon=None):
            sites = [
                x.id for x in Site.objects.exclude(polygon=None) if x.polygon.valid
            ]
            valid_sites = Site.objects.filter(id__in=sites)
            geojson = json.loads(
                valid_sites.exclude(polygon=None)
                .aggregate(combined=Union("polygon"))["combined"]
                .convex_hull.geojson
            )
            geojson["properties"] = {
                "name": "Convex hull of all {} objects".format(self.__name__)
            }
            geojson = json.dumps(geojson)
            return geojson
        else:
            None

    def copy_instance(self):
        """Saves a copy of the current object and returns it"""
        obj = self
        obj.id = None
        obj.pk = None
        old_name = "{}".format(self.name)
        if old_name:
            obj.name = "COPY OF {}".format(old_name)
        else:
            obj.name = "COPY of some other Object"
        obj.save()
        return obj

    class Meta:
        abstract = True


@modify_fields(
    name={
        "verbose_name": "Period name",
        "help_text": "The name of the period (e.g. Iron Age, Early Iron Age, Hallstatt A…).",
    }
)
@reversion.register()
class Period(IadBaseClass):
    """Please provide a definition of this class"""

    start_date = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Earliest beginning of the period (BC).",
        help_text="Must be a number!",
    )
    start_date_latest = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Latest beginning of the period (BC).",
        help_text="Must be a number!",
    )
    end_date = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Earliest end of the period (BC).",
        help_text="Must be a number!",
    )
    end_date_latest = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Latest end of the period (BC).",
        help_text="Must be a number!",
    )
    norm_id = models.CharField(
        blank=True, null=True, max_length=250, verbose_name="PeriodO"
    )
    region = models.ManyToManyField(
        Place,
        blank=True,
        related_name="has_related_period_region",
        verbose_name="Region in which this period is used in.",
        help_text="Region in which this period is used in.",
    )
    country = models.ForeignKey(
        Place,
        blank=True,
        null=True,
        related_name="has_related_period_country",
        verbose_name="Country in which this period is used in.",
        help_text="Country in which this period is used in.",
        on_delete=models.SET_NULL,
    )
    bibl = models.TextField(
        blank=True, null=True, verbose_name="Bibliographic source for this period."
    )

    class Meta:
        ordering = ["pk"]
        verbose_name = "Chronology"

    def get_geojson(self):
        geojson = serialize(
            "geojson",
            Period.objects.filter(id=self.id),
            geometry_field="polygon",
            fields=(
                "name",
                "identifier",
            ),
        )
        return geojson

    @classmethod
    def get_listview_url(self):
        return reverse("browsing:browse_periods")

    # @classmethod
    # def get_createview_url(self):
    #     return reverse('archiv:period_create')

    def get_next(self):
        next = Period.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = Period.objects.filter(id__lt=self.id).order_by("-id")
        if prev:
            return prev.first().id
        return False

    def get_absolute_url(self):
        return reverse("archiv:period_detail", kwargs={"pk": self.id})

    def __str__(self):
        return "{}".format(self.name)


SITE_OWNERSHIP = (
    ("1 – private", "1 – private"),
    ("2 – public", "2 – public"),
    ("3 – private/public", "3 – private/public"),
    ("4 – information not available", "4 – information not available"),
)

SITE_ACCESSIBILITY = (
    ("1 – accessible by public transport", "1 – accessible by public transport"),
    (
        "2 – accessible for individual tourist groups",
        "2 – accessible for individual tourist groups",
    ),
    ("3 – inaccessible", "3 – inaccessible "),
    ("4 – information not available", "4 – information not available"),
)

SITE_VISIBILITY = (
    (
        "1 – reconstructed and interpreted onsite",
        "1 – reconstructed and interpreted onsite",
    ),
    ("2 – visible, but not interpreted", "2 – visible, but not interpreted"),
    ("3 - invisible archaeological heritage", "3 - invisible archaeological heritage"),

archiv/templates/archiv/create_base_template.html
{% extends "webpage/base.html" %}
{% block title %}{% endblock %}
{% load leaflet_tags %}
{% load crispy_forms_tags %}
{% block scriptHeader %}
    {% leaflet_js plugins="forms" %}
    {% leaflet_css plugins="forms" %}
    <style>

        .leaflet-container {  /* all maps */
            width:  100%;
            height: 800px;
        }
        label { font-weight: bold; }

</style>
{% endblock %}
{% block content %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<!-- <div class="container"> -->

    <div class="card">
        <div class="card-header {{self_model_name}}-page">
            {% block objectType %} {% endblock %}
        </div>
        <div class="card-body">
             {% crispy form %}
        </div>
    </div>



{% endblock content %}

archiv/templates/archiv/find_create.html
{% extends "webpage/base.html" %}
{% block title %} Create/Modify Find{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<div class="panel panel-default">
    <div class="panel-heading">
        <h1>Create/Edit Find</h1>
    </div>
    <div class="panel-body">
         {% crispy form %}
    </div>
</div>
</div>
{% endblock content %}

archiv/templates/archiv/monumentprotection_detail.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% load leaflet_tags %}
{% load archiv_extras %}
{% block title %}Monument Protection{% endblock %}
{% block scriptHeader %}
    {% leaflet_js %}
    {% leaflet_css %}
{% endblock %}
{% block content %}
<style>
    .leaflet-container {  /* all maps */
        width:  100%;
        height: 800px;
    }
</style>
<!-- <div class="container"> -->
<div class="row">
<div class="col-md-6">
    <div class="card">
        <div class="card-header monumentprotection-page">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'archiv:monumentprotection_detail' pk=object.get_prev %}">
                                <i class="bi bi-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small><a href="{{ object.get_listview_url }}">Monument Protection</a></small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'archiv:monumentprotection_edit' pk=object.id %}">
                                    <i class="bi bi-pencil-square" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'archiv:monumentprotection_delete' pk=object.id %}">
                                    <i class="bi bi-trash3" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                    {% if user.is_authenticated %}
                        {% class_dict as classes %}
                        <form action="{% url 'archiv:copy_poly' %}">
                            <div class="form-group">
                                <strong>Copy polygon to:</strong>
                                <select class="custom-select" name="target-class" id="target-class">
                                    {% for key, value in classes.items %}
                                        <option value="{{ key }}">{{ value }}</option>
                                    {% endfor %}
                                </select>
                                <input id="current-id" name="current-id" type="hidden" value="{{ object.id }}">
                                <input id="current-class" name="current-class" type="hidden" value="MonumentProtection">
                            </div>
                            <button type="submit" class="btn btn-primary">Copy</button>
                        </form>
                    {% endif %}

                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'archiv:monumentprotection_detail' pk=object.get_next %}" style="float:right">
                        <i class="bi bi-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="card-body">
                <legend><!--add soemthing here--></legend>
                <table class="table table-bordered table-hover">
                    {% if object.site_id %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "site_id" %}
                            </th>
                            <td>
                                <a href="{{ object.site_id.get_absolute_url }}">{{ object.site_id }}</a>
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.threats.all %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "threats" %}
                            </th>
                            <td>
                                {% for x in object.threats.all %}
                                    <li>
                                    <abbr data-toggle="tooltip" data-placement="right" data-html="true" title="{% skos_info x %}">
                                        {{ x }}
                                    </abbr>
                                    </li>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.current_land_use.all %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "current_land_use" %}
                            </th>
                            <td>
                                {% for x in object.current_land_use.all %}
                                    <li>
                                        <abbr data-toggle="tooltip" data-placement="right" data-html="true" title="{% skos_info x %}">
                                        {{ x }}
                                        </abbr>
                                    </li>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.heritage_status %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "heritage_status" %}
                            </th>
                            <td>
                                {{ object.heritage_status }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.natural.heritage_status %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "natural.heritage_status" %}
                            </th>
                            <td>
                                {{ object.natural.heritage_status }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.identifier %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "identifier" %}
                            </th>
                            <td>
                                {{ object.identifier }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.alt_name.all %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "alt_name" %}
                            </th>
                            <td>
                                {% for x in object.alt_name.all %}
                                    <li>
                                        {{x }}
                                    </li>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.alt_id %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "alt_id" %}
                            </th>
                            <td>
                                {{ object.alt_id }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.description %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "description" %}
                            </th>
                            <td>
                                {{ object.description }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.comment %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "comment" %}
                            </th>
                            <td>
                                {{ object.comment }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.public %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "public" %}
                            </th>
                            <td>
                                {{ object.get_public_display }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.literature.all %}
                        <tr>
                            <th class="w-25">
                                {% get_verbose_name monumentprotection "literature" %}
                            </th>
                            <td>
                                {% for x in object.literature.all %}
                                    <li>
                                        {{ x }}
                                    </li>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endif %}
                </table>
    </div>
</div>
</div><!--col-6-->
<div class="col-md-6">
{% leaflet_map "yourmap" callback="window.map_init_basic" %}
                <legend>GeoJSON</legend>
                {{ object.get_geojson }}
</div>
</div><!--main row-->
<!-- </div> -->
<script type="text/javascript">
    var SiteStyle = {
        "color": "#F18C8E",
        "weight": 2,
        "opacity": 1,
        "fillOpacity": 0,
    };

    var ArchEntStyle = {
            "color": "#F0B7A4",
            "weight": 2,
            "opacity": 1,
            "fillOpacity": 0,
        };

    var ArchConvex = {
            "color": "#F0B7A4",
            "weight": 1,
            "opacity": 1,
            "fillOpacity": 0,
    };
    function map_init_basic (map, options) {
        var geojsonFeature = {{ object.get_geojson|safe }};
        L.geoJson(geojsonFeature).addTo(map);
        {% if object.get_site_geojson %}
            var siteGeojsonFeature = {{ object.get_site_geojson|safe }};
            var siteLayer = L.geoJson(siteGeojsonFeature).setStyle(SiteStyle)
            siteLayer.addTo(map);
            map.fitBounds(siteLayer.getBounds());

        {% endif %}
    }
</script>
<script type="text/javascript">
    $('.confirmation').on('click', function () {
        return confirm('Are you sure?');
    });
</script>
{% endblock %}

archiv/templates/archiv/researchquestion_detail.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %}Research Question{% endblock %}
{% block content %}

<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'archiv:researchquestion_detail' pk=object.get_prev %}">
                                <i class="bi bi-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small><a href="{{ object.get_listview_url }}">Research Question</a></small><br>
                        ID {{ object.id }} {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'archiv:researchquestion_edit' pk=object.id %}">
                                    <i class="bi bi-pencil-square" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'archiv:researchquestion_delete' pk=object.id %}">
                                    <i class="bi bi-trash3" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'archiv:researchquestion_detail' pk=object.get_next %}" style="float:right">
                        <i class="bi bi-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="card-body">
                <legend>related Research Activity</legend>
                {% if object.is_research_question_of.all %}
                    <ul>
                        {% for x in object.is_research_question_of.all %}
                            <li>
                                <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            
    </div>
</div>
</div>
{% endblock %}