bib/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = "bib"

urlpatterns = [
    path(
        "reference/detail/<int:pk>",
        views.ReferenceDetailView.as_view(),
        name="reference_detail",
    ),
    path(
        "reference/edit/<int:pk>",
        views.ReferenceUpdate.as_view(),
        name="reference_edit",
    ),
    path(
        "reference/delete/<int:pk>",
        views.ReferenceDelete.as_view(),
        name="reference_delete",
    ),
    path(
        "reference/create/",
        views.ReferenceCreate.as_view(),
        name="reference_create",
    ),
    path("references/", views.ReferenceListView.as_view(), name="browse_references"),
]

iad/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework import routers
from bib.api_views import ZotItemViewSet

from vocabs import api_views
from archiv import api_views as archiv_api_views
from shapes import api_views as shapes_api_vies

router = routers.DefaultRouter()
router.register(r"skoslabels", api_views.SkosLabelViewSet)
router.register(r"skosnamespaces", api_views.SkosNamespaceViewSet)
router.register(r"skosconceptschemes", api_views.SkosConceptSchemeViewSet)
router.register(r"skosconcepts", api_views.SkosConceptViewSet)
router.register(r"ZotItem", ZotItemViewSet)
router.register(r"sites", archiv_api_views.SiteViewSet)
router.register(r"municipalities", shapes_api_vies.MunicipalityViewSet)


urlpatterns = [
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("admin/", admin.site.urls),
    path("browsing/", include("browsing.urls", namespace="browsing")),
    path("vocabs/", include("vocabs.urls", namespace="vocabs")),
    path("vocabs-ac/", include("vocabs.dal_urls", namespace="vocabs-ac")),
    path("archiv-ac/", include("archiv.dal_urls", namespace="archiv-ac")),
    path("entities-ac/", include("entities.dal_urls", namespace="entities-ac")),
    path("entities/", include("entities.urls", namespace="entities")),
    path("shapes/", include("shapes.urls", namespace="shapes")),
    path("shapes-ac/", include("shapes.dal_urls", namespace="shapes-ac")),
    path("bib/", include("bib.urls", namespace="bib")),
    path("bib-ac/", include("bib.dal_urls", namespace="bib-ac")),
    path("archiv/", include("archiv.urls", namespace="archiv")),
    path("checks/", include("checks.urls", namespace="checks")),
    path("", include("webpage.urls", namespace="webpage")),
]

vocabs/urls.py
from django.urls import path
from . import views

app_name = "vocabs"


urlpatterns = [
    path("", views.SkosConceptListView.as_view(), name="skosconcept_list"),
    path("concepts/browse/", views.SkosConceptListView.as_view(), name="browse_vocabs"),
    path(
        "<int:pk>",
        views.SkosConceptDetailView.as_view(),
        name="skosconcept_detail",
    ),
    path("create/", views.SkosConceptCreate.as_view(), name="skosconcept_create"),
    path(
        "update/<int:pk>",
        views.SkosConceptUpdate.as_view(),
        name="skosconcept_update",
    ),
    path(
        "delete/<int:pk>",
        views.SkosConceptDelete.as_view(),
        name="skosconcept_delete",
    ),
    path("scheme/", views.SkosConceptSchemeListView.as_view(), name="browse_schemes"),
    path(
        "scheme/<int:pk>",
        views.SkosConceptSchemeDetailView.as_view(),
        name="skosconceptscheme_detail",
    ),
    path(
        "scheme/create/",
        views.SkosConceptSchemeCreate.as_view(),
        name="skosconceptscheme_create",
    ),
    path(
        "scheme/update/<int:pk>",
        views.SkosConceptSchemeUpdate.as_view(),
        name="skosconceptscheme_update",
    ),
    path(
        "scheme/delete/<int:pk>",
        views.SkosConceptSchemeDelete.as_view(),
        name="skosconceptscheme_delete",
    ),
    path("label/", views.SkosLabelListView.as_view(), name="browse_skoslabels"),
    path(
        "label/<int:pk>",
        views.SkosLabelDetailView.as_view(),
        name="skoslabel_detail",
    ),
    path("label/create/", views.SkosLabelCreate.as_view(), name="skoslabel_create"),
    path(
        "label/update/<int:pk>",
        views.SkosLabelUpdate.as_view(),
        name="skoslabel_update",
    ),
    path(
        "skoslabel/delete/<int:pk>",
        views.SkosLabelDelete.as_view(),
        name="skoslabel_delete",
    ),
    path("vocabs-download/", views.SkosConceptDL.as_view(), name="vocabs-download"),
    path("metadata/", views.MetadataListView.as_view(), name="metadata"),
    path(
        "metadata/<int:pk>",
        views.MetadataDetailView.as_view(),
        name="metadata_detail",
    ),
    path("metadata/create/", views.MetadataCreate.as_view(), name="metadata_create"),
    path(
        "metadata/update/<int:pk>",
        views.MetadataUpdate.as_view(),
        name="metadata_update",
    ),
    path(
        "metadata/delete/<int:pk>",
        views.MetadataDelete.as_view(),
        name="metadata_delete",
    ),
    path(
        "collection/",
        views.SkosCollectionListView.as_view(),
        name="browse_skoscollections",
    ),
    path(
        "collection/<int:pk>",
        views.SkosCollectionDetailView.as_view(),
        name="skoscollection_detail",
    ),
    path(
        "collection/create/",
        views.SkosCollectionCreate.as_view(),
        name="skoscollection_create",
    ),
    path(
        "collection/update/<int:pk>",
        views.SkosCollectionUpdate.as_view(),
        name="skoscollection_update",
    ),
    path(
        "collection/delete/<int:pk>",
        views.SkosCollectionDelete.as_view(),
        name="skoscollection_delete",
    ),
]

vocabs/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django_tables2 import RequestConfig
from .models import SkosConcept, SkosConceptScheme, SkosLabel, SkosCollection, Metadata
from .forms import (
    SkosCollectionForm,
    SkosCollectionFormHelper,
    SkosConceptForm,
    SkosConceptFormHelper,
    SkosConceptSchemeForm,
    SkosConceptSchemeFormHelper,
    SkosLabelForm,
    SkosLabelFormHelper,
    MetadataForm,
)
from .tables import (
    SkosCollectionTable,
    SkosConceptSchemeTable,
    SkosConceptTable,
    SkosLabelTable,
)
from .filters import (
    SkosConceptListFilter,
    SkosConceptSchemeListFilter,
    SkosLabelListFilter,
    SkosCollectionListFilter,
)
from browsing.browsing_utils import GenericListView, BaseCreateView, BaseUpdateView
from .rdf_utils import graph_construct_qs
import time
import datetime
from django.http import HttpResponse


#####################################################
#   Metadata
#####################################################


class MetadataListView(ListView):

    model = Metadata
    template_name = "vocabs/metadata_list.html"


class MetadataDetailView(DetailView):

    model = Metadata
    template_name = "vocabs/metadata_detail.html"


class MetadataCreate(BaseCreateView):

    model = Metadata
    form_class = MetadataForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MetadataCreate, self).dispatch(*args, **kwargs)


class MetadataUpdate(BaseUpdateView):

    model = Metadata
    form_class = MetadataForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MetadataUpdate, self).dispatch(*args, **kwargs)


class MetadataDelete(DeleteView):
    model = Metadata
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("vocabs:metadata")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MetadataDelete, self).dispatch(*args, **kwargs)


#####################################################
#   SkosCollection
#####################################################


class SkosCollectionListView(GenericListView):
    model = SkosCollection
    table_class = SkosCollectionTable
    filter_class = SkosCollectionListFilter
    formhelper_class = SkosCollectionFormHelper
    init_columns = [
        "id",
        "name",
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosCollectionListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [
            x for x in self.get_all_cols() if x not in self.init_columns
        ]
        context["togglable_colums"] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(
            self.request, paginate={"page": 1, "per_page": self.paginate_by}
        ).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosCollectionDetailView(DetailView):

    model = SkosCollection
    template_name = "vocabs/skoscollection_detail.html"


class SkosCollectionCreate(BaseCreateView):

    model = SkosCollection
    form_class = SkosCollectionForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosCollectionCreate, self).dispatch(*args, **kwargs)


class SkosCollectionUpdate(BaseUpdateView):

    model = SkosCollection
    form_class = SkosCollectionForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosCollectionUpdate, self).dispatch(*args, **kwargs)


class SkosCollectionDelete(DeleteView):
    model = SkosCollection
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("vocabs:browse_skoscollections")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosCollectionDelete, self).dispatch(*args, **kwargs)


#####################################################
#   Concept
#####################################################


class SkosConceptListView(GenericListView):
    model = SkosConcept
    table_class = SkosConceptTable
    filter_class = SkosConceptListFilter
    formhelper_class = SkosConceptFormHelper
    init_columns = [
        "id",
        "pref_label",
        "broader_concept",
    ]


class SkosConceptDetailView(DetailView):

    model = SkosConcept
    template_name = "vocabs/skosconcept_detail.html"


class SkosConceptCreate(BaseCreateView):

    model = SkosConcept
    form_class = SkosConceptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptCreate, self).dispatch(*args, **kwargs)


class SkosConceptUpdate(BaseUpdateView):

    model = SkosConcept
    form_class = SkosConceptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptUpdate, self).dispatch(*args, **kwargs)


class SkosConceptDelete(DeleteView):
    model = SkosConcept
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("vocabs:browse_vocabs")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptDelete, self).dispatch(*args, **kwargs)


#####################################################
#   ConceptScheme
#####################################################


class SkosConceptSchemeListView(GenericListView):
    model = SkosConceptScheme
    table_class = SkosConceptSchemeTable
    filter_class = SkosConceptSchemeListFilter
    formhelper_class = SkosConceptSchemeFormHelper
    init_columns = [
        "id",
        "dc_title",
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosConceptSchemeListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [
            x for x in self.get_all_cols() if x not in self.init_columns
        ]
        context["togglable_colums"] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(
            self.request, paginate={"page": 1, "per_page": self.paginate_by}
        ).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table


class SkosConceptSchemeDetailView(DetailView):

    model = SkosConceptScheme
    template_name = "vocabs/skosconceptscheme_detail.html"

    def get_context_data(self, **kwargs):
        context = super(SkosConceptSchemeDetailView, self).get_context_data(**kwargs)
        context["concepts"] = SkosConcept.objects.filter(scheme=self.kwargs.get("pk"))
        return context


class SkosConceptSchemeCreate(BaseCreateView):

    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeCreate, self).dispatch(*args, **kwargs)


class SkosConceptSchemeUpdate(BaseUpdateView):

    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeUpdate, self).dispatch(*args, **kwargs)


class SkosConceptSchemeDelete(DeleteView):
    model = SkosConceptScheme
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("vocabs:browse_schemes")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeDelete, self).dispatch(*args, **kwargs)


###################################################
# SkosLabel
###################################################


class SkosLabelListView(GenericListView):
    model = SkosLabel
    table_class = SkosLabelTable
    filter_class = SkosLabelListFilter
    formhelper_class = SkosLabelFormHelper
    init_columns = [
        "id",
        "name",
    ]

    def get_all_cols(self):
        all_cols = list(self.table_class.base_columns.keys())
        return all_cols

    def get_context_data(self, **kwargs):
        context = super(SkosLabelListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        togglable_colums = [
            x for x in self.get_all_cols() if x not in self.init_columns
        ]
        context["togglable_colums"] = togglable_colums
        return context

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(
            self.request, paginate={"page": 1, "per_page": self.paginate_by}
        ).configure(table)
        default_cols = self.init_columns
        all_cols = self.get_all_cols()
        selected_cols = self.request.GET.getlist("columns") + default_cols
        exclude_vals = [x for x in all_cols if x not in selected_cols]
        table.exclude = exclude_vals
        return table

vocabs/templates/vocabs/metadata_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
    <div class="card-header">
        <h1 style="text-align: center;">Metadata {{ object.title }}
        {% if user.is_authenticated %}
            <small>
                <a href="{% url 'vocabs:metadata_update' pk=object.id %}">
                    <i class="bi bi-pencil-square" title="edit"></i>
                </a>
            </small>
                |
            <small>
                <a href="{% url 'vocabs:metadata_delete' pk=object.id %}">
                    <i class="bi bi-trash3" title="delete"></i>
                </a>
            </small>
         {% endif %}
        </h1>
    </div>
        <table class="table">
        <tr>
        	<th class="w-25">Title</th>
        	<td>{{object.title}}</td>
        </tr>
        <tr>
        	<th>Indentifier</th>
        	<td>{{object.indentifier}}</td>
        </tr>
        <tr>
        	<th>Description</th>
        	<td>{{object.description}}</td>
        </tr>
        <tr>
        	<th>Description language</th>
        	<td>{{object.description_lang}}</td>
        </tr>
        <tr>
        	<th>Language</th>
        	<td>
            {% if object.language %}
        	{% for language in object.language_as_list %}
    		<li>{{ language }}</li>
			{% endfor %}
            {% endif %}
			</td>
        </tr>
        <tr>
        	<th>Version</th>
        	<td>{{object.version}}</td>
        </tr>
        <tr>
        	<th>Creator</th>
        	<td>
            {% if object.creator %}
            {% for creator in object.creator_as_list %}
            <li>{{ creator }}</li>
            {% endfor %}
            {% endif %}  
            </td>
        </tr>
        <tr>
        	<th>Contributor</th>
        	<td>
            {% if object.contributor %}
             {% for contributor in object.contributor_as_list %}
            <li>{{ contributor }}</li>
            {% endfor %}
            {% endif %}   
            </td>
        </tr>
        <tr>
        	<th>Subject</th>
        	<td>
            {% if object.subject %}
        	{% for subject in object.subject_as_list %}
    		<li>{{ subject }}</li>
			{% endfor %}
            {% endif %}
			</td>
        </tr>
        <tr>
        	<th>Owner</th>
        	<td>{{object.owner}}</td>
        </tr>
        <tr>
        	<th>License</th>
        	<td>{{object.license}}</td>
        </tr>
        <tr>
        	<th>Date created</th>
        	<td>{{object.date_created}}</td>
        </tr>
        <tr>
        	<th>Date modified</th>
        	<td>{{object.date_modified}}</td>
        </tr>
        <tr>
        	<th>Date issued</th>
        	<td>{{object.date_issued}}</td>
        </tr>
        <tr>
        	<th>Relation</th>
        	<td>{{object.relation}}</td>
        </tr>
        {% if topConcepts %}
        <tr>
            <th>has Top Concepts</th>
            <td>
                {% for x in topConcepts %}
                <li><a href="{{ x.get_absolute_url }}">{{x}}</a></li>
                {% endfor %}
            </td> 
        </tr>
        {% endif %}
        <tr>
            <th>Download</th>
            <td>
            <li><a href="{% url 'vocabs:vocabs-download' %}">RDF/XML</a></li>
            <li><a href="{% url 'vocabs:vocabs-download' %}?format=turtle">Turtle</a></li>
            </td>
        </tr>
        </table>
   	</div>
</div>
{% endblock %}

vocabs/templates/vocabs/metadata_list.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
{% if object_list %}
{% for x in object_list %}
<div class="card">
    <div class="card-header">
        <h1 style="text-align: center;">Metadata {{ x.title }}
        {% if user.is_authenticated %}
            <small>
                <a href="{% url 'vocabs:metadata_update' pk=x.id %}">
                    <i class="bi bi-pencil-square" title="edit"></i>
                </a>
            </small>
                |
            <small>
                <a href="{% url 'vocabs:metadata_delete' pk=x.id %}">
                    <i class="bi bi-trash3" title="delete"></i>
                </a>
            </small>
         {% endif %}
        </h1>
    </div>
        <table class="table">
        <tr>
        	<th class="w-25">Title</th>
        	<td>{{x.title}}</td>
        </tr>
        <tr>
        	<th>Indentifier</th>
        	<td>{{x.indentifier}}</td>
        </tr>
        <tr>
        	<th>Description</th>
        	<td>{{x.description}}</td>
        </tr>
        <tr>
        	<th>Description language</th>
        	<td>{{x.description_lang}}</td>
        </tr>
        <tr>
        	<th>Language</th>
        	<td>
        	{% if x.language %}
        	{% for language in x.language_as_list %}
    		<li>{{ language }}</li>
			{% endfor %}
			{% endif %}
			</td>
        </tr>
        <tr>
        	<th>Version</th>
        	<td>{{x.version}}</td>
        </tr>
        <tr>
        	<th>Creator</th>
        	<td>
            {% if x.creator %}
            {% for creator in x.creator_as_list %}
            <li>{{ creator }}</li>
            {% endfor %}
            {% endif %}    
            </td>
        </tr>
        <tr>
        	<th>Contributor</th>
        	<td>
            {% if x.contributor %}
            {% for contributor in x.contributor_as_list %}
            <li>{{ contributor }}</li>
            {% endfor %}
            {% endif %} 
            </td>
        </tr>
        <tr>
        	<th>Subject</th>
        	<td>
        	{% if x.subject %}
        	{% for subject in x.subject_as_list %}
    		<li>{{ subject }}</li>
			{% endfor %}
			{% endif %}
			</td>
        </tr>
        <tr>
        	<th>Owner</th>
        	<td>{{x.owner}}</td>
        </tr>
        <tr>
        	<th>License</th>
        	<td>{{x.license}}</td>
        </tr>
        <tr>
        	<th>Date created</th>
        	<td>{{x.date_created}}</td>
        </tr>
        <tr>
        	<th>Date modified</th>
        	<td>{{x.date_modified}}</td>
        </tr>
        <tr>
        	<th>Date issued</th>
        	<td>{{x.date_issued}}</td>
        </tr>
        <tr>
        	<th>Relation</th>
        	<td>{{x.relation}}</td>
        </tr>
        {% if topConcepts %}
        <tr>
            <th>has Top Concepts</th>
            <td>
                {% for x in topConcepts %}
                <li><a href="{{ x.get_absolute_url }}">{{x}}</a></li>
                {% endfor %}
            </td> 
        </tr>
        {% endif %}
        <tr>
            <th>Download</th>
            <td>
            <li><a href="{% url 'vocabs:vocabs-download' %}">RDF/XML</a></li>
            <li><a href="{% url 'vocabs:vocabs-download' %}?format=turtle">Turtle</a></li>
            </td>
        </tr>
        </table>
</div>
{% endfor %}
{% else %}
<a class="btn btn-outline-primary" href="{% url 'vocabs:metadata_create' %}">create Metadata</a>
{% endif %}
</div>
{% endblock %}

vocabs/templates/vocabs/skoscollection_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skoscollection_detail' pk=object.get_prev %}">
                                <i class="bi bi-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>skos:Collection</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skoscollection_update' pk=object.id %}">
                                    <i class="bi bi-pencil-square" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skoscollection_delete' pk=object.id %}">
                                    <i class="bi bi-trash3" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skoscollection_detail' pk=object.get_next %}" style="float:right">
                        <i class="bi bi-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
        <table class="table">
        {% if object.creator %}
         <tr>
            <th class="w-25">dc:creator</th>
            <td>
            {% for creator in object.creator_as_list %}
            <li>{{ creator }}</li>
            {% endfor %}
            </td>
        </tr>
        {% endif %}

        {% if object.skos_note %}
         <tr>
            <th>skos:note</th>
            <td>{{object.skos_note}}</td>
        </tr>
        {% endif %}

        {% if object.skos_scopenote %}
         <tr>
            <th>skos:scopeNote</th>
            <td>{{object.skos_scopenote}}</td>
        </tr>
        {% endif %}

        {% if object.skos_changenote %}
         <tr>
            <th>skos:changeNote</th>
            <td>{{object.skos_changenote}}</td>
        </tr>
        {% endif %}

        {% if object.skos_editorialnote %}
         <tr>
            <th>skos:editorialNote</th>
            <td>{{object.skos_editorialnote}}</td>
        </tr>
        {% endif %}

        {% if object.skos_example %}
         <tr>
            <th>skos:example</th>
            <td>{{object.skos_example}}</td>
        </tr>
        {% endif %}

        {% if object.skos_historynote %}
         <tr>
            <th>skos:historyNote</th>
            <td>{{object.skos_historynote}}</td>
        </tr>
        {% endif %}

        {% if object.date_created %}
         <tr>
            <th class="w-25">dct:created</th>
            <td>{{object.date_created}}</td>
        </tr>
        {% endif %}

        {% if object.date_modified %}
         <tr>
            <th class="w-25">dct:modified</th>
            <td>{{object.date_modified}}</td>
        </tr>
        {% endif %}

        {% if object.has_members.all %}
        <tr>
        <th class="w-25">skos:members</th>
        <td>
        {% for x in object.has_members.all %}
            <li>
                <a href="{{ x.get_absolute_url }}">{{ x }}</a>
            </li>
        {% endfor %}
        </td>
        </tr>
        {% endif %}

        </table>  
    </div>
</div>
{% endblock %}

vocabs/templates/vocabs/skosconcept_filter.html
{% extends "vocabs/generic_list.html" %}
{% block list_title %}Browse SkosConcepts{% endblock %}
{% block create_button %}
{% if user.is_authenticated %}
<div>
    <a class ="btn btn-primary"  href="{% url 'vocabs:skosconcept_create' %}">
        create new concept
    </a>
</div>
{% endif %}
{% endblock %}
{% block reset_button %}
    <a class ="btn btn-outline-secondary" href="{% url 'vocabs:browse_vocabs' %}">reset search</a>
{% endblock %}

vocabs/templates/vocabs/skoslabel_detail.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'vocabs:skoslabel_detail' pk=object.get_prev %}">
                                <i class="bi bi-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>Label</small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'vocabs:skoslabel_update' pk=object.id %}">
                                    <i class="bi bi-pencil-square" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'vocabs:skoslabel_delete' pk=object.id %}">
                                    <i class="bi bi-trash3" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'vocabs:skoslabel_detail' pk=object.get_next %}" style="float:right">
                        <i class="bi bi-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
            <table class="table">
                <tr>
                    <th>Label</th>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <th>Label type</th>
                    <td>{{ object.label_type }}</td>
                </tr>
                <tr>
                    <th>IsoCode</th>
                    <td>{{ object.isoCode }}</td>
                </tr>
            </table>
    </div>
</div>
{% endblock %}