bib/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = "bib"

urlpatterns = [
    path(
        "reference/detail/<int:pk>",
        views.ReferenceDetailView.as_view(),
        name="reference_detail",
    ),
    path(
        "reference/edit/<int:pk>",
        views.ReferenceUpdate.as_view(),
        name="reference_edit",
    ),
    path(
        "reference/delete/<int:pk>",
        views.ReferenceDelete.as_view(),
        name="reference_delete",
    ),
    path(
        "reference/create/",
        views.ReferenceCreate.as_view(),
        name="reference_create",
    ),
    path("references/", views.ReferenceListView.as_view(), name="browse_references"),
]

entities/urls.py
from django.urls import path
from . import views

app_name = "entities"

urlpatterns = [
    path(
        "altnames/",
        views.AlternativeNameListView.as_view(),
        name="alternativename_list",
    ),
    path(
        "altnames/detail/<int:pk>",
        views.AlternativeNameDetailView.as_view(),
        name="alternativename_detail",
    ),
    path(
        "altnames/create/",
        views.AlternativeNameCreate.as_view(),
        name="alternativename_create",
    ),
    path(
        "altnames/edit/<int:pk>",
        views.AlternativeNameUpdate.as_view(),
        name="alternativename_edit",
    ),
    path(
        "altnames/delete/<int:pk>",
        views.AlternativeNameDelete.as_view(),
        name="alternativename_delete",
    ),
    path("place/create/", views.create_place, name="place_create"),
    path(
        "place/detail/<int:pk>",
        views.PlaceDetailView.as_view(),
        name="place_detail",
    ),
    path("place/edit/<int:pk>", views.edit_place, name="place_edit"),
    path(
        "place/delete/<int:pk>",
        views.PlaceDelete.as_view(),
        name="place_delete",
    ),
    path(
        "institution/detail/<int:pk>",
        views.InstitutionDetailView.as_view(),
        name="institution_detail",
    ),
    path(
        "institution/delete/<int:pk>",
        views.InstitutionDelete.as_view(),
        name="institution_delete",
    ),
    path(
        "institution/edit/<int:pk>",
        views.InstitutionUpdate.as_view(),
        name="institution_edit",
    ),
    path(
        "institution/create/",
        views.InstitutionCreate.as_view(),
        name="institution_create",
    ),
    path(
        "persons/create/<int:pk>",
        views.PersonDetailView.as_view(),
        name="person_detail",
    ),
    path("person/create/", views.PersonCreate.as_view(), name="person_create"),
    path(
        "person/edit/<int:pk>",
        views.PersonUpdate.as_view(),
        name="person_edit",
    ),
    path(
        "person/delete/<int:pk>",
        views.PersonDelete.as_view(),
        name="person_delete",
    ),
]

iad/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework import routers
from bib.api_views import ZotItemViewSet

from vocabs import api_views
from archiv import api_views as archiv_api_views
from shapes import api_views as shapes_api_vies

router = routers.DefaultRouter()
router.register(r"skoslabels", api_views.SkosLabelViewSet)
router.register(r"skosnamespaces", api_views.SkosNamespaceViewSet)
router.register(r"skosconceptschemes", api_views.SkosConceptSchemeViewSet)
router.register(r"skosconcepts", api_views.SkosConceptViewSet)
router.register(r"ZotItem", ZotItemViewSet)
router.register(r"sites", archiv_api_views.SiteViewSet)
router.register(r"municipalities", shapes_api_vies.MunicipalityViewSet)


urlpatterns = [
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("admin/", admin.site.urls),
    path("browsing/", include("browsing.urls", namespace="browsing")),
    path("vocabs/", include("vocabs.urls", namespace="vocabs")),
    path("vocabs-ac/", include("vocabs.dal_urls", namespace="vocabs-ac")),
    path("archiv-ac/", include("archiv.dal_urls", namespace="archiv-ac")),
    path("entities-ac/", include("entities.dal_urls", namespace="entities-ac")),
    path("entities/", include("entities.urls", namespace="entities")),
    path("shapes/", include("shapes.urls", namespace="shapes")),
    path("shapes-ac/", include("shapes.dal_urls", namespace="shapes-ac")),
    path("bib/", include("bib.urls", namespace="bib")),
    path("bib-ac/", include("bib.dal_urls", namespace="bib-ac")),
    path("archiv/", include("archiv.urls", namespace="archiv")),
    path("checks/", include("checks.urls", namespace="checks")),
    path("", include("webpage.urls", namespace="webpage")),
]

entities/models.py
from django.db import models
from django.urls import reverse
from idprovider.models import IdProvider

BOOLEAN_CHOICES = ((True, "Yes"), (False, "No"))


class AlternativeName(IdProvider):
    name = models.CharField(max_length=250, blank=True, help_text="Alternative Name")

    def get_absolute_url(self):
        return reverse("entities:alternativename_detail", kwargs={"pk": self.id})

    @classmethod
    def get_listview_url(self):
        return reverse("browsing:browse_altnames")

    @classmethod
    def get_createview_url(self):
        return reverse("entities:alternativename_create")

    def get_next(self):
        next = AlternativeName.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = AlternativeName.objects.filter(id__lt=self.id).order_by("-id")
        if prev:
            return prev.first().id
        return False

    def __str__(self):
        return "{}".format(self.name)


class Place(IdProvider):
    PLACE_TYPES = (("city", "city"), ("country", "country"))

    """Holds information about entities."""
    name = models.CharField(max_length=250, blank=True, help_text="Normalized name")
    alt_names = models.ManyToManyField(
        AlternativeName,
        max_length=250,
        blank=True,
        help_text="Alternative names",
        related_name="altname_of_place",
    )
    geonames_id = models.CharField(max_length=50, blank=True, help_text="GND-ID")
    lat = models.DecimalField(max_digits=20, decimal_places=12, blank=True, null=True)
    lng = models.DecimalField(max_digits=20, decimal_places=12, blank=True, null=True)
    part_of = models.ForeignKey(
        "Place",
        null=True,
        blank=True,
        help_text="A place (country) this place is part of.",
        related_name="has_child",
        on_delete=models.CASCADE,
    )
    place_type = models.CharField(
        choices=PLACE_TYPES, null=True, blank=True, max_length=50
    )

    def get_geonames_url(self):
        if self.geonames_id.startswith("ht") and self.geonames_id.endswith(".html"):
            return self.geonames_id
        elif self.geonames_id.startswith("ht"):
            return self.geonames_id
        else:
            return "http://www.geonames.org/{}".format(self.geonames_id)

    def get_geonames_rdf(self):
        return None

    def save(self, *args, **kwargs):
        if self.geonames_id:
            new_id = self.get_geonames_url()
            self.geonames_id = new_id
        super(Place, self).save(*args, **kwargs)

    @classmethod
    def get_listview_url(self):
        return reverse("browsing:browse_places")

    @classmethod
    def get_createview_url(self):
        return reverse("entities:place_create")

    def get_next(self):
        next = Place.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = Place.objects.filter(id__lt=self.id).order_by("-id")
        if prev:
            return prev.first().id
        return False

    def get_absolute_url(self):
        return reverse("entities:place_detail", kwargs={"pk": self.id})

    def __str__(self):
        return "{}".format(self.name)


class Institution(IdProvider):
    legacy_id = models.CharField(max_length=300, blank=True, verbose_name="Legacy ID")
    written_name = models.CharField(
        max_length=300, blank=True, verbose_name="Written name"
    )
    inst_alt_name = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="Alternative Name(s) for this Institution",
        help_text="Use '; ' to separate many alterantive names.",
    )
    authority_url = models.CharField(
        max_length=300, blank=True, verbose_name="Authority url"
    )
    adress = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="Adress",
        help_text="Adress of the research institution/museum.",
    )
    contact = models.CharField(
        max_length=200,
        blank=True,
        verbose_name="Contact",
        help_text="Contact (email) of the research institution/museum.",
    )
    homepage = models.CharField(
        max_length=200,
        blank=True,
        verbose_name="Homepage",
        help_text="URL of the research institution/museum.",
    )
    alt_names = models.ManyToManyField(
        AlternativeName,
        max_length=250,
        blank=True,
        related_name="altname_of_inst",
        verbose_name="Alternative names",
    )
    abbreviation = models.CharField(
        max_length=300, blank=True, verbose_name="Abbreviation"
    )
    location = models.ForeignKey(
        Place, blank=True, null=True, on_delete=models.CASCADE, verbose_name="Location"
    )
    parent_institution = models.ForeignKey(
        "Institution",
        blank=True,
        null=True,
        related_name="children_institutions",
        on_delete=models.CASCADE,
        verbose_name="Parent institution",
    )
    comment = models.TextField(blank=True, verbose_name="Comment")

    @classmethod
    def get_listview_url(self):
        return reverse("browsing:browse_institutions")

    @classmethod
    def get_createview_url(self):
        return reverse("entities:institution_create")

    def get_absolute_url(self):
        return reverse("entities:institution_detail", kwargs={"pk": self.id})

    def get_next(self):
        next = Institution.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = Institution.objects.filter(id__lt=self.id).order_by("-id")
        if prev:
            return prev.first().id
        return False

    def __str__(self):
        return "{}".format(self.written_name)


class Person(IdProvider):
    legacy_id = models.CharField(max_length=300, blank=True, verbose_name="Legacy ID")
    written_name = models.CharField(
        max_length=300, blank=True, verbose_name="Written name"
    )
    forename = models.CharField(max_length=300, blank=True, verbose_name="Forename")
    name = models.CharField(max_length=300, blank=True, verbose_name="Name")
    pers_alt_name = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="Alternative Name(s) for this Person",
        help_text="Use '; ' to separate many alterantive names.",
    )
    acad_title = models.CharField(
        max_length=300, blank=True, verbose_name="Academic title"
    )
    alt_names = models.ManyToManyField(
        AlternativeName,
        max_length=250,
        blank=True,
        related_name="altname_of_persons",
        verbose_name="Alternative names",
    )
    belongs_to_institution = models.ForeignKey(
        Institution,
        blank=True,
        null=True,
        related_name="has_member",
        on_delete=models.CASCADE,
        verbose_name="Belongs to institution",
    )
    place_of_birth = models.ForeignKey(
        Place,
        blank=True,
        null=True,
        related_name="is_birthplace",
        on_delete=models.CASCADE,
        verbose_name="Place of Birth",
    )
    date_of_birth = models.DateField(
        auto_now=False,
        auto_now_add=False,
        blank=True,
        null=True,
        verbose_name="Date of Birth",
        help_text="YYYY-MM-DD",
    )
    authority_url = models.CharField(
        max_length=300, blank=True, verbose_name="Authority url"
    )
    comment = models.TextField(blank=True, verbose_name="Comment")
    public = models.BooleanField(
        default=False,
        verbose_name="Public",
        choices=BOOLEAN_CHOICES,
        help_text="Should this entry (and all related entries) be public\
        or only visible to the account holders? Can be made public\
        only after data-check was completed.",
    )

    class Meta:
        verbose_name = "Researcher"

    @classmethod
    def get_createview_url(self):
        return reverse("entities:person_create")

    @classmethod
    def get_listview_url(self):
        return reverse("browsing:browse_persons")

    def get_absolute_url(self):
        return reverse("entities:person_detail", kwargs={"pk": self.id})

    def get_next(self):
        next = Person.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = Person.objects.filter(id__lt=self.id).order_by("-id")
        if prev:
            return prev.first().id
        return False

    def __str__(self):
        if self.written_name:
            return "{}".format(self.written_name)
        elif self.name and self.forename:
            return "{}, {}".format(self.name, self.forename)
        elif self.name:
            return "{}".format(self.name)
        else:
            return "No name provided"

entities/forms.py
# -*- coding: utf-8 -*-
from django import forms
from dal import autocomplete
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Place, AlternativeName, Institution, Person


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        exclude = [
            "alt_names",
        ]
        widgets = {
            "belongs_to_institution": autocomplete.ModelSelect2(
                url="entities-ac:institution-autocomplete"
            ),
            "place_of_birth": autocomplete.ModelSelect2(
                url="entities-ac:place-autocomplete"
            ),
            "alt_names": autocomplete.ModelSelect2Multiple(
                url="entities-ac:altname-autocomplete"
            ),
            "date_of_birth": forms.DateInput(
                attrs={"placeholder": "YYYY-MM-DD"}, format=("%Y-%m-%d")
            ),
        }

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.add_input(
            Submit("submit", "save"),
        )


class InstitutionForm(forms.ModelForm):
    class Meta:
        model = Institution
        exclude = [
            "alt_names",
        ]
        widgets = {
            "location": autocomplete.ModelSelect2(url="entities-ac:place-autocomplete"),
            "parent_institution": autocomplete.ModelSelect2(
                url="entities-ac:institution-autocomplete"
            ),
            "alt_names": autocomplete.ModelSelect2Multiple(
                url="entities-ac:altname-autocomplete"
            ),
        }

    def __init__(self, *args, **kwargs):
        super(InstitutionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.add_input(
            Submit("submit", "save"),
        )


class AlternativeNameForm(forms.ModelForm):
    class Meta:
        model = AlternativeName
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(AlternativeNameForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.add_input(
            Submit("submit", "save"),
        )


class AlternativeNameFormCreate(forms.ModelForm):
    class Meta:
        model = AlternativeName
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(AlternativeNameFormCreate, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False


class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = "__all__"
        widgets = {
            "part_of": autocomplete.ModelSelect2(url="entities-ac:place-autocomplete"),
            "alt_names": autocomplete.ModelSelect2Multiple(
                url="entities-ac:altname-autocomplete"
            ),
        }

    def __init__(self, *args, **kwargs):
        super(PlaceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False


class PlaceFormCreate(forms.ModelForm):
    class Meta:
        model = Place
        fields = "__all__"
        widgets = {
            "part_of": autocomplete.ModelSelect2(url="entities-ac:place-autocomplete"),
            "alt_names": autocomplete.ModelSelect2Multiple(
                url="entities-ac:altname-autocomplete"
            ),
        }

    def __init__(self, *args, **kwargs):
        super(PlaceFormCreate, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"

entities/templates/entities/alternativenames_detail.html
{% extends "webpage/base.html" %}
{% load static %}
{% block Title %}Edit Places{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to
include 'autocomplete_light/static.html
-->
<!--leafletjs -->
<link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
<script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
<style>
#map { height: 500px; }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                    <h2>
                        <a href="{% url 'entities:alternativename_detail' pk=object.get_prev %}">
                            <i class="bi bi-chevron-left" title="previous"></i>
                        </a>
                    </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small><a href="{{ object.get_listview_url }}">alternative name</a></small> {{ object.name }}
                        {% if user.is_authenticated %}
                        <small><a href="{% url 'entities:alternativename_edit' pk=object.id %}">
                            <i class="bi bi-pencil-square" title="edit"></i>
                        </a>
                    </small>
                    {% endif %}
                </h1>
            </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'entities:alternativename_detail' pk=object.get_next %}" style="float:right">
                        <i class="bi bi-chevron-right" title="next"></i>
                    </a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="card-body">
                <legend>About</legend>
                <table class="table table-bordered table-hover">
                <tr>
                    <th>related places</th>
                    <td>
                        <ul>
                            {% for x in object.related_places.all %}
                            {% if x.id %}
                            <li><a href="{% url 'entities:place_detail' pk=x.id %}">{{ x }}</a></li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            </tbody>
        </table>
        {% if user.is_authenticated %}
            <a class="btn btn-danger" href="{% url 'entities:alternativename_delete' pk=object.id %}">delete</a>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

entities/templates/entities/edit_places.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% load leaflet_tags %}
{% block Title %}Edit Places{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to
    include 'autocomplete_light/static.html
-->
<!--leafletjs -->
    {% leaflet_js %}
    {% leaflet_css %}
        <style>
            #map { height: 800px; }
        </style>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

{% if object %}
<div class="row">
    <div class="col-md-4">
{% endif %}
        <div class="card">
            <div class="card-header">
                  <h1>{%if object %} Edit {{ object.name }} {% else %} Create Place {% endif %}</h1>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% crispy form %}
                    {% if object %}
                    <a class="btn btn-outline-secondary btn-block" target="_blank" rel="noopener">Check<span id="currentID"></span></a>
                    {% endif %}
                    <input class="btn btn-primary" type="submit" value="Save" />
                    {% if object %}
                    <a class ="btn btn-danger btn-sm" href="{% url 'entities:place_delete' pk=object.id %}">delete</a>
                    {% endif %}
                </form>
           </div>
       </div>
{% if object %}
   </div>
    <div class ="col-md-8">
        <div class="card">
            <div class="card-header">
                <form class="form-group">
                    <select class="form-control" id="geonamesSELECT">
                            {% if object.geonames_id or object.lat %}
                                <option id="geonamesOption" value="{{ object.name }}_{{ object.lat }}_{{ object.lng }}_{{ object.geonames_id }}">DB-Entry | {{ object.name }} | {{ object.lat }} | {{ object.lng }} | {{ object.geonames_id }}</option>
                            {% endif %}
                            {% for dict in responseJSON %}
                            <option id="geonamesOption" value="{{ dict.countryName }}_{{ dict.name }}_{{ dict.lat }}_{{ dict.lng }}_{{ dict.geonameId }}"> {{ dict.countryName }} | {{ dict.name }} | {{ dict.lat }} | {{ dict.lng }} | {{ dict.geonameId }}</option>
                            {% endfor %}
                        </select>
                    </form>
            </div>
            <div class="card-body">
                <div id="parentMap"></div>
            </div>
        </div>
    </div>
</div>
{% endif %}


{% if object %}
<script type="text/javascript">
    $( document ).ready(function() {
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 10);

       L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1IjoiY3NhZTgwOTIiLCJhIjoiY2lnM2FoZWpjMDJqZnY1a2gxdWl6a29kaiJ9.FQXlsKIu60WhiXLrfI59VA'
        }).addTo(map);

        L.marker([gps1, gps2]).addTo(map)
        .bindPopup(placeName)
        .openPopup();
        });
</script>


<script type="text/javascript">
    $( document ).ready(function(){
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(geonameId);
        console.log(geonameId)
        if (String(geonameId).startsWith('http')) {
            var gndURL = geonameId.trim();
        }   else {
            gndURL = "http://www.geonames.org/"+geonameId.trim();
        }
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href", gndURL);

    });
</script>

<script type="text/javascript">
    $("#geonamesSELECT").change(function(){
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 15);
        var geonameId = placeName.split(/\|/)[4].trim();
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val((geonameId));
        if (String(geonameId).startsWith('http')) {
            var gndURL = geonameId.trim();
        }   else {
            gndURL = "http://www.geonames.org/"+geonameId.trim();
        }
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href", gndURL);

       L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1IjoiY3NhZTgwOTIiLCJhIjoiY2lnM2FoZWpjMDJqZnY1a2gxdWl6a29kaiJ9.FQXlsKIu60WhiXLrfI59VA'
        }).addTo(map);

        L.marker([gps1, gps2]).addTo(map)
            .bindPopup(placeName)
            .openPopup();
});
</script>
{% endif %}
{% endblock %}

entities/templates/entities/list_places.html
{% extends "webpage/base.html" %}
{% load static %}
{% block Title %}List of Places{% endblock %}

{% block scriptHeader %}<!--leafletjs -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}
{% block content %}
{% if object_list %}
  <div class="row">
    <div class="col-md-4">
        <div class="card" >
            <div class="card-header" style="text-align:center;">
                <h3>Places</h3>
          {% if user.is_authenticated %}
            <a href="{% url 'entities:place_create' %}">(add another Place)</a>
          {% endif %}
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>GeoNames</th>
                        </th>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                        <tr>
                            <td>
                {% if user.is_authenticated %}
                  <a href="{% url 'entities:place_edit' pk=object.id %}">{{ object }} (edit)</a>
                  {% else %}
                  {{ object }}
                {% endif %}
              </td>
                            <td>{{ object.geonames_id }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header" style="text-align:center;">
                <h3>Geovisualisation</h3>
            </div>
            <div class="card-body">
                <div id="parentMap"></div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $( document ).ready(function() {
         $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");

        var map = L.map('map').setView([48.69096, 9.14062], 5);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1IjoiY3NhZTgwOTIiLCJhIjoiY2lnM2FoZWpjMDJqZnY1a2gxdWl6a29kaiJ9.FQXlsKIu60WhiXLrfI59VA'
        }).addTo(map);

        {% for object in object_list %}
        {% if object.lat %}
        L.marker([{{ object.lat }}, {{ object.lng }}])
        .addTo(map)
        .bindPopup("<h1>{{ object.name }}</h1> <table class='table table-striped'> <tr> <td>Name: </td> <td>{{ object.name }}</td> </tr> </table>");
        {% endif %}
        {% endfor %}
        });
</script>
{% else %}

  {% if user.is_authenticated %}
  <div class="card">
        <div class="card-header">
            <h1>Places</h1>
            <div>
                <a class="btn btn-primary" href="{% url 'entities:place_create' %}" role="button">
                    crate a new location/place
                </a>
            </div>
            <br />
        </div>
        <div class="card-body">
        </div>
    </div>

  {% endif %}
{% endif %}
{% endblock %}