bib/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = "bib"

urlpatterns = [
    path(
        "reference/detail/<int:pk>",
        views.ReferenceDetailView.as_view(),
        name="reference_detail",
    ),
    path(
        "reference/edit/<int:pk>",
        views.ReferenceUpdate.as_view(),
        name="reference_edit",
    ),
    path(
        "reference/delete/<int:pk>",
        views.ReferenceDelete.as_view(),
        name="reference_delete",
    ),
    path(
        "reference/create/",
        views.ReferenceCreate.as_view(),
        name="reference_create",
    ),
    path("references/", views.ReferenceListView.as_view(), name="browse_references"),
]

iad/urls.py
from django.urls import path, include
from django.contrib import admin
from rest_framework import routers
from bib.api_views import ZotItemViewSet

from vocabs import api_views
from archiv import api_views as archiv_api_views
from shapes import api_views as shapes_api_vies

router = routers.DefaultRouter()
router.register(r"skoslabels", api_views.SkosLabelViewSet)
router.register(r"skosnamespaces", api_views.SkosNamespaceViewSet)
router.register(r"skosconceptschemes", api_views.SkosConceptSchemeViewSet)
router.register(r"skosconcepts", api_views.SkosConceptViewSet)
router.register(r"ZotItem", ZotItemViewSet)
router.register(r"sites", archiv_api_views.SiteViewSet)
router.register(r"municipalities", shapes_api_vies.MunicipalityViewSet)


urlpatterns = [
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("admin/", admin.site.urls),
    path("browsing/", include("browsing.urls", namespace="browsing")),
    path("vocabs/", include("vocabs.urls", namespace="vocabs")),
    path("vocabs-ac/", include("vocabs.dal_urls", namespace="vocabs-ac")),
    path("archiv-ac/", include("archiv.dal_urls", namespace="archiv-ac")),
    path("entities-ac/", include("entities.dal_urls", namespace="entities-ac")),
    path("entities/", include("entities.urls", namespace="entities")),
    path("shapes/", include("shapes.urls", namespace="shapes")),
    path("shapes-ac/", include("shapes.dal_urls", namespace="shapes-ac")),
    path("bib/", include("bib.urls", namespace="bib")),
    path("bib-ac/", include("bib.dal_urls", namespace="bib-ac")),
    path("archiv/", include("archiv.urls", namespace="archiv")),
    path("checks/", include("checks.urls", namespace="checks")),
    path("", include("webpage.urls", namespace="webpage")),
]

bib/models.py
# -*- coding: utf-8 -*-
from django.urls import reverse
from django.db import models


class ZotItem(models.Model):
    """Stores main bibliographic information of a Zotero Item"""

    zot_key = models.CharField(
        max_length=20,
        primary_key=True,
        verbose_name="key",
        help_text="The Zotero Item Key",
    )
    zot_creator = models.TextField(
        blank=True,
        verbose_name="creators",
        help_text="Stores all information from zoteros 'creators' field.",
    )
    zot_date = models.TextField(
        blank=True,
        verbose_name="date",
        help_text="Stores all information from zoteros 'date' field.",
    )
    zot_item_type = models.TextField(
        blank=True,
        verbose_name="itemType",
        help_text="Stores all information from zoteros 'itemType' field.",
    )
    zot_title = models.TextField(
        blank=True,
        verbose_name="title",
        help_text="Stores all information from zoteros 'title' field.",
    )
    zot_pub_title = models.TextField(
        blank=True,
        verbose_name="publicationTitle",
        help_text="Stores all information from zoteros 'publicationTitle' field.",
    )
    date_modified = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name="dateModified",
        help_text="Stores all information from zoteros 'publicationTitle' field.",
    )
    zot_pages = models.TextField(
        blank=True,
        verbose_name="pages",
        help_text="Stores all information from zoteros 'pages' field.",
    )
    zot_version = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="version",
        help_text="Stores all information from zoteros 'pages' field.",
    )
    zot_html_link = models.CharField(
        blank=True,
        verbose_name="selflink html",
        max_length=500,
        help_text="Stores all information from zoteros 'selflink' field.",
    )
    zot_api_link = models.CharField(
        blank=True,
        verbose_name="selflink api",
        max_length=500,
        help_text="Stores all information from zoteros self api link field.",
    )
    zot_bibtex = models.TextField(
        blank=True,
        verbose_name="bibtex",
        help_text="Stores the item's bibtex representation.",
    )

    class Meta:
        ordering = ["-zot_version"]

    def __str__(self):
        if self.zot_bibtex:
            return "{}".format(self.zot_bibtex)
        elif (
            self.zot_title and self.zot_creator and self.zot_pub_title and self.zot_date
        ):
            return "title: {}; pub-title: {}; creator(s): {}; year: {}".format(
                self.zot_title, self.zot_pub_title, self.zot_creator, self.zot_date
            )
        elif self.zot_title and self.zot_creator and self.zot_pub_title:
            return "title: {}; pub-title: {}; creator(s): {}; year: no date provided".format(
                self.zot_title, self.zot_pub_title, self.zot_creator
            )
        elif self.zot_creator and self.zot_pub_title:
            return "title: no title provided;\
            pub-title: {}; creator(s): {}; year: no date provided".format(
                self.zot_pub_title, self.zot_creator
            )
        else:
            return "{}".format(self.zot_key)

    def get_zotero_url(self):
        "Returns the objects URL pointing to its Zotero entry"
        if self.zot_html_link:
            return self.zot_html_link
        else:
            return None


class Reference(models.Model):
    """Contains a precise bibliographic reference"""

    zotero_item = models.ForeignKey(
        ZotItem,
        blank=True,
        null=True,
        verbose_name="Zotero Item",
        help_text="Select the zotero item you would like to quote",
        related_name="has_references",
        on_delete=models.SET_NULL,
    )
    page = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="Page Number",
        help_text="Page Number",
    )

    class Meta:
        ordering = ["-id"]

    @classmethod
    def get_listview_url(self):
        return reverse("bib:browse_references")

    @classmethod
    def get_createview_url(self):
        return reverse("bib:reference_create")

    def get_next(self):
        next = Reference.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = Reference.objects.filter(id__lt=self.id).order_by("-id")
        if prev:
            return prev.first().id
        return False

    def get_absolute_url(self):
        return reverse("bib:reference_detail", kwargs={"pk": self.id})

    def __str__(self):
        try:
            return "{}, {}".format(self.zotero_item, self.page)
        except:  # noqa: E722
            return "{}".format(self.id)

bib/forms.py
from dal import autocomplete
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Reference


class ReferenceForm(forms.ModelForm):
    class Meta:
        model = Reference
        fields = "__all__"
        widgets = {
            "zotero_item": autocomplete.ModelSelect2(url="bib-ac:book-autocomplete")
        }

    def __init__(self, *args, **kwargs):
        super(ReferenceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.add_input(
            Submit("submit", "save"),
        )

bib/views.py
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import Reference
from .forms import ReferenceForm


class ReferenceListView(ListView):
    model = Reference
    template_naem = "bib/reference_list.html"

    def get_context_data(self, **kwargs):
        context = super(ReferenceListView, self).get_context_data(**kwargs)
        context["docstring"] = "{}".format(self.model.__doc__)
        if self.model._meta.verbose_name_plural:
            context["class_name"] = "{}".format(self.model._meta.verbose_name.title())
        else:
            if self.model.__name__.endswith("s"):
                context["class_name"] = "{}".format(self.model.__name__)
            else:
                context["class_name"] = "{}s".format(self.model.__name__)
        try:
            context["create_view_link"] = self.model.get_createview_url()
        except AttributeError:
            context["create_view_link"] = None
        try:
            context["download"] = self.model.get_dl_url()
        except AttributeError:
            context["download"] = None
        model_name = self.model.__name__.lower()
        context["entity"] = model_name
        context["count"] = self.get_queryset().count()
        return context


class BaseCreateView(CreateView):
    model = None
    form_class = None
    template_name = "bib/generic_create.html"

    def get_context_data(self, **kwargs):
        context = super(BaseCreateView, self).get_context_data()
        context["docstring"] = "{}".format(self.model.__doc__)
        if self.model.__name__.endswith("s"):
            context["class_name"] = "{}".format(self.model.__name__)
        else:
            context["class_name"] = "{}s".format(self.model.__name__)
        return context


class BaseUpdateView(UpdateView):
    model = None
    form_class = None
    template_name = "archiv/generic_create.html"

    def get_context_data(self, **kwargs):
        context = super(BaseUpdateView, self).get_context_data()
        context["docstring"] = "{}".format(self.model.__doc__)
        if self.model.__name__.endswith("s"):
            context["class_name"] = "{}".format(self.model.__name__)
        else:
            context["class_name"] = "{}s".format(self.model.__name__)
        return context


class ReferenceDetailView(DetailView):
    model = Reference
    template_name = "bib/reference_detail.html"


class ReferenceCreate(BaseCreateView):

    model = Reference
    form_class = ReferenceForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ReferenceCreate, self).dispatch(*args, **kwargs)


class ReferenceUpdate(BaseUpdateView):

    model = Reference
    form_class = ReferenceForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ReferenceUpdate, self).dispatch(*args, **kwargs)


class ReferenceDelete(DeleteView):
    model = Reference
    template_name = "webpage/confirm_delete.html"
    success_url = reverse_lazy("browsing:browse_references")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ReferenceDelete, self).dispatch(*args, **kwargs)

bib/templates/bib/generic_create.html
{% extends "archiv/create_base_template.html" %}
{% block title %}
    Create/Edit {{ class_name }}
{% endblock %}

{% block objectType %}
    <h1>Create/Edit
        {% if docstring %}
            <abbr title="{{ docstring}}">{{ class_name }}</abbr>
        {% else %}
            {{ class_name }}
        {% endif %}
    </h1>
{% endblock %}

bib/templates/bib/reference_detail.html
{% extends "webpage/base.html" %}
{% load static %}
{% load leaflet_tags %}
{% load webpage_extras %}
{% block title %}Reference {{ object.id }}{% endblock %}
{% block scriptHeader %}
    {% leaflet_js %}
    {% leaflet_css %}
{% endblock %}
{% block content %}

<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                        <h2>
                            <a href="{% url 'bib:reference_detail' pk=object.get_prev %}">
                                <i class="bi bi-chevron-left" title="previous"></i>
                            </a>
                        </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small><a href="{{object.get_listview_url }}">Reference:</a></small> {{ object }}
                        {% if user.is_authenticated %}
                            <small>
                                <a href="{% url 'bib:reference_edit' pk=object.id %}">
                                    <i class="bi bi-pencil-square" title="edit"></i>
                                </a>
                            </small>
                            |
                            <small>
                                <a href="{% url 'bib:reference_delete' pk=object.id %}">
                                    <i class="bi bi-trash3" title="delete"></i>
                                </a>
                            </small>
                        {% endif %}
                    </h1>
                </div>
                <div class="col-md-2">
                    <h2>
                        {% if object.get_next %}
                        <a href="{% url 'bib:reference_detail' pk=object.get_next %}" style="float:right">
                            <i class="bi bi-chevron-right" title="next"></i>
                        </a>
                    </h2>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-hover">
                <tr>
                    <th>
                        {% get_verbose_name reference "zotero_item" %}
                    </th>
                    <td>
                        {{ object.zotero_item }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {% get_verbose_name reference "page" %}
                    </th>
                    <td>
                        {{ object.page }}
                    </td>
                </tr>
            </table>
        </div>
        <footer style="text-align: center;">
            <a href="{{ object.zotero_item.get_zotero_url }}">view <i class="fas fa-book"></i> at Zotero</a>
        </footer>

    </div>
</div>
{% endblock %}

bib/templates/bib/reference_list.html
{% extends "webpage/base.html" %}
{% load static %}
{% load leaflet_tags %}
{% load webpage_extras %}
{% block title %}References{% endblock %}
{% block scriptHeader %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
{% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header" style="text-align:center;">
            <h1>{{ count }} References</h1><br />
            {% if user.is_authenticated %}
            {% if create_view_link  %}
              <a class ="btn btn-outline-secondary"  href="{{ create_view_link }}">Create new {{class_name}}</a>
            {% endif %}
            {% endif %}
        </div>
        <div class="card-body">
            <table id="example" class="table display" style="width:100%">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Pub-Title</th>
                        <th>Date</th>
                        <th>Pages</th>
                        <th>Zotero-Key</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in object_list %}
                        <tr>
                            <td>
                                {{ x.zotero_item.zot_title }}
                            </td>
                            <td>
                                {{ x.zotero_item.zot_pub_title }}
                            </td>
                            <td>
                                {{ x.zotero_item.zot_date }}
                            </td>
                            <td>
                                {{ x.zotero_item.zot_pages }}
                            </td>
                            <td>
                                <a href="{{ x.get_absolute_url }}">{{ x.zotero_item.zot_key }}</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    <script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
    </script>
{% endblock %}

bib/templates/bib/synczotero.html
{% extends "webpage/base.html" %}
{% load bib_extras %}

{% block content %}
<div class="container" style="text-align:center;">
	<a class ="btn btn-primary btn-lg"  href="{% url 'bib:synczotero_update' %}">Synchronize</a>
</div>

{% endblock %}

bib/templates/bib/synczotero_action.html
{% extends "webpage/base.html" %}
{% load bib_extras %}
{% block content %}
<div class="container">
	<h1>Results</h1>
	<table class="table table-hover">
		<tr>
			<th>books in db before update operation:</th>
			<td>{{ books_before }}<td>
		</tr>
		<tr>
			<th>books in db after update operation:</th>
			<td>{{ books_after }}<td>
		</tr>
		<tr>
			<th>updated</th>
			<td>
                {% if saved %}
                    {% for x in saved %}
                        <li>
                            {% bib_quote x %}
                        </li>
                    {% endfor %}
                {% else %}
                    no updates
                {% endif %}
			</td>
		</tr>

	</table>
</div>

{% endblock %}